var annotated_dup =
[
    [ "_loader_data", "struct__loader__data.html", "struct__loader__data" ],
    [ "_saver_data", "struct__saver__data.html", "struct__saver__data" ],
    [ "BitmapInfo", "structBitmapInfo.html", "structBitmapInfo" ],
    [ "CLIST", "structCLIST.html", "structCLIST" ],
    [ "CONTRIB", "structCONTRIB.html", "structCONTRIB" ],
    [ "Image", "structImage.html", "structImage" ],
    [ "libsndfile_context", "structlibsndfile__context.html", "structlibsndfile__context" ],
    [ "my_error_mgr", "structmy__error__mgr.html", "structmy__error__mgr" ],
    [ "oggvorbis_reader_context", "structoggvorbis__reader__context.html", "structoggvorbis__reader__context" ],
    [ "simage_image_s", "structsimage__image__s.html", "structsimage__image__s" ],
    [ "simage_movie_exporter", "structsimage__movie__exporter.html", "structsimage__movie__exporter" ],
    [ "simage_movie_importer", "structsimage__movie__importer.html", "structsimage__movie__importer" ],
    [ "simage_movie_s", "structsimage__movie__s.html", "structsimage__movie__s" ],
    [ "simage_open_funcs", "structsimage__open__funcs.html", "structsimage__open__funcs" ],
    [ "simage_param_data", "structsimage__param__data.html", "structsimage__param__data" ],
    [ "simage_parameters_s", "structsimage__parameters__s.html", "structsimage__parameters__s" ],
    [ "simage_plugin", "structsimage__plugin.html", "structsimage__plugin" ],
    [ "simage_rgb_opendata", "structsimage__rgb__opendata.html", "structsimage__rgb__opendata" ],
    [ "simage_stream_exporter", "structsimage__stream__exporter.html", "structsimage__stream__exporter" ],
    [ "simage_stream_importer", "structsimage__stream__importer.html", "structsimage__stream__importer" ],
    [ "simage_stream_s", "structsimage__stream__s.html", "structsimage__stream__s" ],
    [ "simage_tiff_opendata", "structsimage__tiff__opendata.html", "structsimage__tiff__opendata" ]
];