#!/bin/sh

# XXX debug
echo >> msvc.txt
date +%H:%M:%S >> msvc.txt
echo "in: \"$@\"" >> msvc.txt

cl_options="/nologo"
cl_c_is_used=false
cl_next_is_object=false
# FIXME: handle multiple sourcefiles. 20001009 mortene.
cl_basename_source=

for msvc_option in $@
do
  case $msvc_option in
  -E) # Run preprocessor
    cl_options="$cl_options /E"
    ;;
  -c) # Compile objectfile
    cl_c_is_used=true
    cl_options="$cl_options /c"
    ;;
  -o) # Name object- or executable file
    if $cl_c_is_used; then
      cl_options="$cl_options /Fo" # name object file
    else
      cl_options="$cl_options /Fe" # name executable file
    fi
    cl_next_is_object=true
    ;;
  *.c) # C file
    cl_basename_source=`basename $msvc_option`
    cl_sourcefile_name=`cygpath -w $msvc_option`
    cl_options="$cl_options /Tc$cl_sourcefile_name" # force compilation as C
    ;;
  *.cpp | *.cxx | *.c++ | *.cc) # C++ file
    cl_basename_source=`basename $msvc_option`
    cl_sourcefile_name=`cygpath -w $msvc_option`
    cl_options="$cl_options /Tp$cl_sourcefile_name" # force compilation as C++
    ;;
  -I*)
    cl_inc_path=`echo $msvc_option | sed 's%^..%%'`
    cl_options="$cl_options /I`cygpath -w $cl_inc_path`"
    ;;
  -L*)
    cl_ld_path=`echo $msvc_option | sed 's%^..%%'`
    cl_options="$cl_options /L`cygpath -w $cl_ld_path`"
    ;;
  -l*)
    cl_base_libname=`echo $msvc_option | sed 's%^..%%'`
    cl_options="$cl_options $cl_base_libname.lib"
    ;;
  *)
    if $cl_next_is_object; then
      cl_options="$cl_options$msvc_option"
      cl_next_is_object=false
    else
      cl_options="$cl_options $msvc_option"
    fi
    ;;
  esac
done

# XXX debug
echo "out: \"$cl_options\"" >> msvc.txt

cl_stdout=$$.out
cl_stderr=$$.err
cl.exe $cl_options >$cl_stdout 2>$cl_stderr
cl_exit_code=$?
grep -v "^$cl_basename_source\$" < $cl_stdout
grep -v "^$cl_basename_source\$" >&2 < $cl_stderr
rm -f $cl_stdout
rm -f $cl_stderr

exit $cl_exit_code
