#! /bin/sh

# XXX debug
echo >> msvc.txt
date +%H:%M:%S >> msvc.txt
echo "in: \"$@\"" >> msvc.txt

options="/nologo"
c_is_used=false
next_is_object=false
# FIXME: handle multiple sourcefiles. 20001009 mortene.
basename_source=
msvc_tool=

for msvc_option in $@
do
  case $msvc_option in
  -E) # Run preprocessor
    options="$options /E"
    ;;
  -D*) # Preprocessor define.
    options="$options /`echo $msvc_option | sed s%^.%%`"
    ;;
  -c) # Compile objectfile
    c_is_used=true
    options="$options /c"
    ;;
  -o) # Name object- or executable file
    if $c_is_used; then
      options="$options /Fo" # name object file
    else
      options="$options /Fe" # name executable file
    fi
    # FIXME: couldn't we just "shift in" the object file? 20001018 mortene.
    next_is_object=true
    ;;
  *.c) # C file
    basename_source=`basename $msvc_option`
    sourcefile_name=`cygpath -w $msvc_option`
    options="$options /Tc$sourcefile_name" # force compilation as C
    ;;
  *.cpp | *.cxx | *.c++ | *.cc) # C++ file
    basename_source=`basename $msvc_option`
    sourcefile_name=`cygpath -w $msvc_option`
    options="$options /Tp$sourcefile_name" # force compilation as C++
    ;;
  -I*)
    inc_path=`echo $msvc_option | sed 's%^..%%'`
    options="$options /I`cygpath -w $inc_path`"
    ;;
  -L*)
    ld_path=`echo $msvc_option | sed 's%^..%%'`
    # FIXME: /L is not the correct option, I think. 20001018 mortene.
    options="$options /L`cygpath -w $ld_path`"
    ;;
  -l*)
    base_libname=`echo $msvc_option | sed 's%^..%%'`
    options="$options $base_libname.lib"
    ;;
  -link | -LINK | /link | /LINK)
    # FIXME: assert msvc_tool="". 20001018 mortene.
    # FIXME: is this correct or should it be lib.exe? 20001018 mortene.
    msvc_tool=lib.exe
    ;;
  -dll | /dll | /DLL)
    # FIXME: "-DLL" has a different semantic, should we warn? 20001018 mortene.
    # FIXME: assert that msvc_tool="". 20001018 mortene.
    msvc_tool=link.exe
    ;;

  /OUT:* | /out:*)
    # FIXME: collect pass-through options somehow? 20001018 mortene.
    options="$options $msvc_option"
    ;;

  -* | /*)
    echo "ERROR: unknown option \"$msvc_option\""
    exit 1
    ;;

  *) # Regular disk files (sourcecode files, object files, library files, ..)
    # FIXME: follow file links as lib.exe at least doesn't handle them.
    # 20001018 mortene.
    if $next_is_object; then
      options="$options$msvc_option"
      next_is_object=false
    else
      options="$options $msvc_option"
    fi
    ;;
  esac
done

test -z "$msvc_tool" && msvc_tool=cl.exe

# XXX debug
echo "out: $msvc_tool $options" >> msvc.txt

stdout=$$.out
stderr=$$.err
$msvc_tool $options >$stdout 2>$stderr
exit_code=$?
grep -v "^$basename_source\$" < $stdout
grep -v "^$basename_source\$" >&2 < $stderr
rm -f $stdout
rm -f $stderr

exit $exit_code
