#! /bin/sh
# **************************************************************************
# This is a script for retrieving configuration information about the
# installed simage libraries on the system.
#
# Authors:
#   Morten Eriksen <mortene@coin3d.org>
#   Lars J. Aas <larsa@coin3d.org>
#

me=`echo "$0" | sed 's,^.*[/\\],,g'`
wd=`echo "$0" | sed 's,/[^/]*$,,'`
# wd=`cd "$wd"; pwd`
prefix=`cd "$wd/.."; pwd`

alternate=default

for arg
do
  case $arg in
  --alternate=*) alternate=`echo $arg | cut -d= -f2-` ;;
  esac
done

if test -f $prefix/share/Coin/conf/simage-$alternate.cfg; then
  . $prefix/share/Coin/conf/simage-$alternate.cfg
elif test -f $prefix/share/Coin/conf/simage-default.cfg; then
  . $prefix/share/Coin/conf/simage-default.cfg
else
  echo >&2 "$me: no default simage config available"
  exit 1
fi

usage="\
Usage: $me [OPTIONS]
Options:
  --alternate=<string>
  --cppflags
  --ldflags
  --libs
  --build <program> <sourcefile> [<sourcefile>]...
  --version
  --usage | --help"

while test $# -gt 0
do
  case $1 in
  --help | --usage) echo "$usage" ;;
  --version)        echo "$version" ;;
  --cppflags)       echo "$cppflags" ;;
  --ldflags)        echo "$ldflags" ;;
  --libs)           echo "$libs" ;;
  --build)
    shift
    program=$1
    shift
    exec $compiler \
      $CPPFLAGS $cppflags \
      $LDFLAGS $ldflags \
      -o $program $@ \
      $LIBS $libs
    ;;
  # ignore some options
  --alternate=*) ;;
  *)
    echo >&2 "$me: Invalid option: \"$1\""
    echo >&2 "$usage"
    exit 1
    ;;
  esac
  shift
done

exit 0

